spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml